export { default as Dashboard } from "./Dashboard";
export { default as SubmitForm } from "./SubmitForm";
export { default as Kanban } from "./Kanban";
export { default as OperatorSubmit } from "./OperatorSubmit";
export { default as OperatorLogin } from "./OperatorLogin";
export { default as TechnicianSubmit } from "./TechnicianSubmit";
export { default as TechnicianLogin } from "./TechnicianLogin";
export { default as Login } from "./Login";
export { default as Start } from "./Start";
// export { default as Employees } from "./Employees";
export { default as Forms } from "./Forms";
export { default as Calendar } from "./Calendar";
export { default as Area } from "./Charts/Area";
export { default as Bar } from "./Charts/Bar";
export { default as ColorMapping } from "./Charts/ColorMapping";
export { default as Line } from "./Charts/Line";
export { default as Pie } from "./Charts/Pie";
export { default as Stacked } from "./Charts/Stacked";
